version: "3.8"

services:
  backend:
    image: 11xenon11/secondbrain:${LATEST_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - "2233:2233"
